// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYYMqBmhf75zilVfCsfgHpT9WyspLUnI',
    appId: '1:27371757920:web:845f673371477d0539be05',
    messagingSenderId: '27371757920',
    projectId: 'uxeloft-7ec44',
    authDomain: 'uxeloft-7ec44.firebaseapp.com',
    storageBucket: 'uxeloft-7ec44.appspot.com',
    measurementId: 'G-0HKP4JN3JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDF4O5xLAn6mnVGycNfJWy0J4C_420nIA',
    appId: '1:239648144863:android:b25fee0d52943825bd186a',
    messagingSenderId: '239648144863',
    projectId: 'myprojects-7cbf6',
    storageBucket: 'myprojects-7cbf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1fY7UD7V2YKPoH8NmjWF9d3-YwhC_FPI',
    appId: '1:239648144863:ios:5819af9f2eaf6d0fbd186a',
    messagingSenderId: '239648144863',
    projectId: 'myprojects-7cbf6',
    storageBucket: 'myprojects-7cbf6.appspot.com',
    iosBundleId: 'machinetest.com.machineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDeO_bL87xbw7q0sofcEH5Jf4YuoavVWE',
    appId: '1:27371757920:ios:748707b4f599ee9039be05',
    messagingSenderId: '27371757920',
    projectId: 'uxeloft-7ec44',
    storageBucket: 'uxeloft-7ec44.appspot.com',
    iosBundleId: 'machinetest.com.machineTest.RunnerTests',
  );
}